language: c++
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0

matrix:
  include:
    - os: osx
      env: COMPILER=g++
      compiler: g++
    - os: osx
      env: COMPILER=clang++
      compiler: clang++
    - os: linux
      env: COMPILER=g++-6
      compiler: g++-6
      addons: { apt: { packages: [g++-6], sources: [ubuntu-toolchain-r-test]}}
    - os: linux
      addons: { apt: { packages: [clang-3.6], sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise, llvm-toolchain-precise-3.6]}}
      env: COMPILER=clang++-3.6
      compiler: clang++-3.6
    - os: linux
      addons: { apt: { packages: [clang-3.7], sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise, llvm-toolchain-precise-3.7]}}
      env: COMPILER=clang++-3.7
      compiler: clang++-3.7

install:
 - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
 - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
 - if [[ "${BOOST_VERSION}" == "" ]]; then BOOST_VERSION=1.62.0; fi
 - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CMAKE_CXX_COMPILER=${COMPILER}; fi
 # install modern boost
 - |
   if [[ "${BOOST_VERSION}" != "" ]]; then
     BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
     if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
       if [[ "${BOOST_VERSION}" == "trunk" ]]; then
         BOOST_URL="http://github.com/boostorg/boost.git"
         travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} ${BOOST_DIR} || exit 1
         (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers)
       else
         BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
         mkdir -p ${BOOST_DIR}
         { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
       fi
     fi
     CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
   fi
 # install modern cmake
 - |
   if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
     CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
     mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
     export PATH=${DEPS_DIR}/cmake/bin:${PATH}
   else
     if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
   fi
 - cd ..

script:
 - mkdir build
 - cd build
 - cmake ${CMAKE_OPTIONS} .. && make

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313fib\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"

