language: cpp
addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake
compiler:
 - clang
 - gcc
script:
 - mkdir build
 - cd build
 - cmake .. && make
notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313fib\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"

