language: c++
sudo: false

matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: g++
      env: COMPILER=g++

    - os: osx
      compiler: clang++
      env: COMPILER=clang++ DOCS=ON

    - os: linux
      compiler: g++
      dist: trusty
      env: COMPILER=g++ DOCS=ON
      addons:
        apt:
          packages:
            - doxygen
            - libboost-context-dev
            - libevent-dev

    - os: linux
      compiler: clang++
      dist: trusty
      env: COMPILER=clang++
      addons:
        apt:
          packages:
            - libboost-context-dev
            - libevent-dev

    - os: linux
      compiler: g++-6
      dist: trusty
      env: COMPILER=g++-6
      addons:
        apt:
          packages:
            - g++-6
            - libboost-context-dev
            - libevent-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: clang++-3.6
      dist: trusty
      env: COMPILER=clang++-3.6
      addons:
        apt:
          packages:
            - clang-3.6
            - libboost-context-dev
            - libevent-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      compiler: clang++-3.7
      dist: trusty
      env: COMPILER=clang++-3.7
      addons:
        apt:
          packages:
            - clang-3.7
            - libboost-context-dev
            - libevent-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

before_install:
 - echo ${CC}
 - ${COMPILER} -v
 - cmake --version

install:
 - |
   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
     if ! brew ls --version boost &>/dev/null; then brew install boost; fi
     if ! brew ls --version libevent &>/dev/null; then brew install libevent; fi
     if [[ "${DOCS} == "ON" ]]; then
       if ! brew ls --version doxygen &>/dev/null; then brew install doxygen; fi
     fi
   fi
 - |
   if [[ "${DOCS} == "ON" ]]; then
     export CMAKE_OPTIONS="$CMAKE_OPTIONS -DENABLE_DOCS=ON"
   fi

script:
 - mkdir build
 - cd build
 - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_COMPILER="${COMPILER}" .. && make

notifications:
  irc:
    channels: ["irc.freenode.org#haskell-lens"]
    skip_join: true
    template: ["\x0313fib\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"]
