language: c++
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0

matrix:
  include:
    - os: osx
      env: COMPILER=g++
      compiler: g++

    - os: osx
      env: COMPILER=clang++
      compiler: clang++

    - os: linux
      env: COMPILER=g++-6
      compiler: g++-6
      addons:
        apt:
          packages: [g++-6, libboost-all-dev, libboost-context-dev, libevent-dev]
          sources: [ubuntu-toolchain-r-test]

    - os: linux
      env: COMPILER=clang++-3.6
      compiler: clang++-3.6
      addons: 
        apt:
          packages: [clang-3.6, libboost-all-dev, libboost-context-dev, libevent-dev]
          sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise, llvm-toolchain-precise-3.6]

    - os: linux
      env: COMPILER=clang++-3.7
      compiler: clang++-3.7
      addons:
        apt:
          packages: [clang-3.7, libboost-all-dev, libboost-context-dev, libevent-dev]
          sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise, llvm-toolchain-precise-3.7]

before_install:
 - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
 - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CMAKE_CXX_COMPILER=${COMPILER}; fi
 - ${CMAKE_CXX_COMPILER} -v
 # _system_ cmake version
 - cmake --version

install:
 - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
 - |
   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
     if ! brew ls --version boost &>/dev/null; then brew install boost; fi
   fi
 - |
   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
     if ! brew ls --version libevent &>/dev/null; then brew install libevent; fi
   fi
 - |
   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
     if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
   else
     CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
     mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
     export PATH=${DEPS_DIR}/cmake/bin:${PATH}
     cmake --version
   fi
 - cd ..

script:
 - mkdir build
 - cd build
 - cmake ${CMAKE_OPTIONS} .. && make

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313fib\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"

